name: '.Net Code Coverage Badge'
description: 'Extact code coverage percentage from an cobertura report and generates metadata for a shields.io badge'
branding:
  icon: 'award'  
  color: 'yellow'
  
inputs:
  label:
    description: 'The badge label. For example "Unit Test Coverage"'
    required: false
    default: 'Test Coverage'
  color:
    description: 'The color of the badge. See https://shields.io/ for options'
    required: false
    default: 'brightgreen'
  path:
    description: 'the path to the cobertura.xml file'
    required: true
  gist-filename:
    description: 'Filename of the Gist used for storing the badge data'
    required: false
  gist-id:
    description: 'ID if the Gist used for storing the badge data'
    required: false
  gist-auth-token:
    description: 'Auth token that alows to write to the given Gist'
    required: false

outputs:
  percentage:
    description: 'The code coverage percentage'
  badge:
    description: 'The badge data as in json format as required by shields.io'

runs:
  using: 'node12'
  main: 'index.js'
